[project]
name = "shared-code-environment"
version = "0.1.0"
description = "Shared code environment for UK LISA work"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dynesty",
    "nessai",
    "astropy",
    "numpy",
    "scipy",
    "bbhx",
    "fastemriwaveforms",
    "eryn",
    "lisaconstants",
    "fastlisaresponse",
    "gbgpu",
    "pycbc",
    "lisaglitch",
    "pyEFPE @ git+https://github.com/gmorras/pyEFPE.git",
    "lisagap @ git+https://github.com/ollieburke/lisagap.git",
    "phenomxpy @ git+https://github.com/imrphenom-dev/phenomxpy.git",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"
